import type { Metadata } from "next";
import { Kumbh_Sans } from "next/font/google";
import "./globals.css";
import AppLayout from "./components/AppLayout";
import { getServerSession } from "next-auth";
import { authOptions } from "./api/auth/[...nextauth]/route";

const kumbh = Kumbh_Sans({ subsets: ["latin"], variable: "--kumbh_sans" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession(authOptions);

  return (
    <html lang="en">
      <body className={`${kumbh.className}`}>
        <AppLayout session={session}>
          {children}
        </AppLayout>
      </body>
    </html>
  );
}